REM REM @@echo off
rem Note: Need to run from JavaRelated directory.
set LOCAL_HOME=.
set LIB_HOME=%LOCAL_HOME%\lib
set LIBJARS=%LOCAL_HOME%\bin;..\MDP\bin
set DOMAIN_HOME="files\final_comp\rddl"
set PLANNER="rddl.solver.mdp.sbisimulation.FullPartitionWithADDAndLRTDPForMDP"
set INSTANCE_NAME="navigation_inst_mdp__1"
for %%i in (%LIB_HOME%\*.jar) do call %LOCAL_HOME%\cpappend.bat %%i

for /l %%c in (1, 1, 1) do (
rem  2.Algorithms below are used to solve a reduced MDP with the complete set of states.
	rem value iteration (MDP M')
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "crossing_traffic_inst_mdp__1"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "crossing_traffic_inst_mdp__2"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "elevators_inst_mdp__1"
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "elevators_inst_mdp__2"
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "elevators_inst_mdp__3"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "elevators_inst_mdp__4"
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "elevators_inst_mdp__7"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "game_of_life_inst_mdp__1"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "game_of_life_inst_mdp__2"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "game_of_life_inst_mdp__3"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__1"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__6"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__8"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__9"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "navigation_inst_mdp__10"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "skill_teaching_inst_mdp__1"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "skill_teaching_inst_mdp__2"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "skill_teaching_inst_mdp__3"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "skill_teaching_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "skill_teaching_inst_mdp__5"
	rem  java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithValueIteration" "skill_teaching_inst_mdp__6"
	rem topological value iteration (MDP M')
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "crossing_traffic_inst_mdp__1"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "crossing_traffic_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "crossing_traffic_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "crossing_traffic_inst_mdp__4"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "elevators_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "elevators_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "elevators_inst_mdp__3"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "elevators_inst_mdp__7"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "game_of_life_inst_mdp__1"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "game_of_life_inst_mdp__2"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "game_of_life_inst_mdp__3"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__1"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__6"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__8"
	 rem vjava -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__9"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "navigation_inst_mdp__10"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__1"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__2"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__3"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__6"
	rem Labeled Real-Time Dynamic Programming (MDP M')
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "crossing_traffic_inst_mdp__1"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "crossing_traffic_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "crossing_traffic_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "crossing_traffic_inst_mdp__4"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "elevators_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "elevators_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "elevators_inst_mdp__3"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "elevators_inst_mdp__7" +/- 2h
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "game_of_life_inst_mdp__1"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "game_of_life_inst_mdp__2"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "game_of_life_inst_mdp__3"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__1"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__6"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__8"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__9"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "navigation_inst_mdp__10"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "skill_teaching_inst_mdp__1"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "skill_teaching_inst_mdp__2"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "skill_teaching_inst_mdp__3"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "skill_teaching_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "skill_teaching_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.MRFSWithLRTDP" "skill_teaching_inst_mdp__6"
rem )

rem for /l %%c in (1, 1, 8) do (
	rem  2.Algorithms below are used to solve a reduced MDP with reachable states.
	rem value iteration (MDP M')
	rem  java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "crossing_traffic_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "crossing_traffic_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "crossing_traffic_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "crossing_traffic_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "elevators_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "elevators_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "elevators_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "elevators_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "game_of_life_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "game_of_life_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "game_of_life_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__6"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__8"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__9"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "navigation_inst_mdp__10"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "skill_teaching_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "skill_teaching_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "skill_teaching_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "skill_teaching_inst_mdp__4"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "skill_teaching_inst_mdp__5"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithValueIteration" "skill_teaching_inst_mdp__6"
	rem topological value iteration (MDP M')
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "crossing_traffic_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "crossing_traffic_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "crossing_traffic_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "crossing_traffic_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "elevators_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "elevators_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "elevators_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "elevators_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "game_of_life_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "game_of_life_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "game_of_life_inst_mdp__3"
	 java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "game_of_life_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__6"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__8"
	 rem vjava -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__9"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "navigation_inst_mdp__10"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithTopologicalValueIteration" "skill_teaching_inst_mdp__6"
	rem Labeled Real-Time Dynamic Programming (MDP M')
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "crossing_traffic_inst_mdp__1"
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "crossing_traffic_inst_mdp__2"
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "crossing_traffic_inst_mdp__3"
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "crossing_traffic_inst_mdp__4"
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "elevators_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "elevators_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "elevators_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "elevators_inst_mdp__7" REM +/- 2h
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "game_of_life_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "game_of_life_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "game_of_life_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__6"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__8"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__9"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "navigation_inst_mdp__10"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "skill_teaching_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "skill_teaching_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "skill_teaching_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "skill_teaching_inst_mdp__4"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "skill_teaching_inst_mdp__5"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files\final_comp\rddl" "rddl.solver.mdp.sbisimulation.ReachMRFSWithLRTDP" "skill_teaching_inst_mdp__6"
rem )

rem for /l %%c in (1, 1, 10) do (
	rem 1.Algorithms in this section are to solve the original MDP M
	rem VI (MDP M)
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "crossing_traffic_inst_mdp__1" 
	rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "crossing_traffic_inst_mdp__2" 
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "elevators_inst_mdp__1" 
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "navigation_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "navigation_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "game_of_life_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "game_of_life_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "game_of_life_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "skill_teaching_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.EnumerativeVI" "skill_teaching_inst_mdp__2"
	rem TVI (MDP M)
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "crossing_traffic_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "crossing_traffic_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "crossing_traffic_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "crossing_traffic_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "elevators_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "elevators_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "elevators_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "elevators_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "game_of_life_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "game_of_life_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "game_of_life_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__6"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__8"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__9"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "navigation_inst_mdp__10"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "skill_teaching_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "skill_teaching_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "skill_teaching_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "skill_teaching_inst_mdp__4"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "skill_teaching_inst_mdp__5"
	 REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.vi.TVI_FTVI" "skill_teaching_inst_mdp__6"
	rem LRTDP (MDP M)
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "crossing_traffic_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "crossing_traffic_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "crossing_traffic_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "crossing_traffic_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "elevators_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "elevators_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "elevators_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "elevators_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "elevators_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "game_of_life_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "game_of_life_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "game_of_life_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__4"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__5"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__6"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__7"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__8"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__9"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "navigation_inst_mdp__10"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "skill_teaching_inst_mdp__1"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "skill_teaching_inst_mdp__2"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "skill_teaching_inst_mdp__3"
	 rem java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "skill_teaching_inst_mdp__4"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "skill_teaching_inst_mdp__5"
	REM java -Xms3072M -Xmx3072M -classpath %LIBJARS% rddl.sim.Simulator "files/final_comp/rddl" "rddl.solver.mdp.rtdp.off_LRTDPEnum" "skill_teaching_inst_mdp__6"
	 
)
